import type { MonsterDef } from "@/types";

export const MONSTER_CATALOG: MonsterDef[] = [
  {
    id: "goblin-scout",
    name: "Goblin Scout",
    level: 1,
    hp: 30,
    attack: 8,
    defense: 2,
    xpReward: 20,
    goldReward: 10,
    lootTable: [
      { itemId: "worn-sword",            chance: 0.18 },
      { itemId: "leather-vest",          chance: 0.12 },
      { itemId: "health-charm",          chance: 0.10 },
      { itemId: "minor-health-potion",   chance: 0.15 },
    ],
    description: "A small, quick goblin — your first real test.",
  },
  {
    id: "giant-rat",
    name: "Giant Rat",
    level: 1,
    hp: 22,
    attack: 9,
    defense: 1,
    xpReward: 18,
    goldReward: 8,
    lootTable: [
      { itemId: "stamina-band",          chance: 0.18 },
      { itemId: "health-charm",          chance: 0.14 },
      { itemId: "minor-health-potion",   chance: 0.15 },
    ],
    description: "Fast and feral. Low defense but bites hard.",
  },
  {
    id: "forest-goblin",
    name: "Forest Goblin",
    level: 2,
    hp: 45,
    attack: 10,
    defense: 3,
    xpReward: 32,
    goldReward: 16,
    lootTable: [
      { itemId: "worn-sword",            chance: 0.20 },
      { itemId: "hunters-bow",           chance: 0.15 },
      { itemId: "leather-vest",          chance: 0.14 },
      { itemId: "minor-health-potion",   chance: 0.18 },
      { itemId: "health-potion",         chance: 0.08 },
    ],
    description: "Armed with a crude axe and a chip on its shoulder.",
  },
  {
    id: "orc-grunt",
    name: "Orc Grunt",
    level: 3,
    hp: 60,
    attack: 13,
    defense: 5,
    xpReward: 50,
    goldReward: 25,
    lootTable: [
      { itemId: "hunters-bow",           chance: 0.20 },
      { itemId: "padded-robe",           chance: 0.18 },
      { itemId: "iron-sword",            chance: 0.10 },
      { itemId: "health-potion",         chance: 0.12 },
    ],
    description: "Thick-skinned and relentless. Respect the club.",
  },
  {
    id: "cave-spider",
    name: "Cave Spider",
    level: 4,
    hp: 50,
    attack: 15,
    defense: 3,
    xpReward: 65,
    goldReward: 33,
    lootTable: [
      { itemId: "stamina-band",          chance: 0.22 },
      { itemId: "twin-daggers",          chance: 0.12 },
      { itemId: "chain-shirt",           chance: 0.10 },
      { itemId: "health-potion",         chance: 0.10 },
    ],
    description: "Venomous and fast. It will overwhelm the unprepared.",
  },
  {
    id: "skeleton-warrior",
    name: "Skeleton Warrior",
    level: 5,
    hp: 80,
    attack: 15,
    defense: 7,
    xpReward: 85,
    goldReward: 43,
    lootTable: [
      { itemId: "chain-shirt",           chance: 0.20 },
      { itemId: "iron-sword",            chance: 0.18 },
      { itemId: "warriors-pendant",      chance: 0.12 },
      { itemId: "health-potion",         chance: 0.12 },
    ],
    description: "Animated by dark magic. High defense — chip it down.",
  },
  {
    id: "dark-wolf",
    name: "Dark Wolf",
    level: 6,
    hp: 90,
    attack: 18,
    defense: 5,
    xpReward: 105,
    goldReward: 53,
    lootTable: [
      { itemId: "twin-daggers",          chance: 0.22 },
      { itemId: "stamina-band",          chance: 0.20 },
      { itemId: "shadowweave-cloak",     chance: 0.08 },
      { itemId: "phantom-blades",        chance: 0.05 },
      { itemId: "greater-health-potion", chance: 0.08 },
    ],
    description: "Hunts in shadows. Ferocious and hungry.",
  },
  {
    id: "stone-troll",
    name: "Stone Troll",
    level: 7,
    hp: 120,
    attack: 20,
    defense: 9,
    xpReward: 135,
    goldReward: 68,
    lootTable: [
      { itemId: "battle-plate",          chance: 0.22 },
      { itemId: "warriors-pendant",      chance: 0.20 },
      { itemId: "iron-sword",            chance: 0.18 },
      { itemId: "titan-plate",           chance: 0.06 },
      { itemId: "greater-health-potion", chance: 0.10 },
    ],
    description: "Nearly indestructible. Bring your best stats.",
  },
  {
    id: "dark-mage",
    name: "Dark Mage",
    level: 8,
    hp: 80,
    attack: 25,
    defense: 4,
    xpReward: 160,
    goldReward: 80,
    lootTable: [
      { itemId: "arcane-tome",           chance: 0.22 },
      { itemId: "ring-of-wisdom",        chance: 0.20 },
      { itemId: "staff-of-ages",         chance: 0.10 },
      { itemId: "void-tome",             chance: 0.07 },
      { itemId: "greater-health-potion", chance: 0.10 },
    ],
    description: "Glass cannon. Kill it fast or get obliterated.",
  },
  {
    id: "ancient-dragon",
    name: "Ancient Dragon",
    level: 10,
    hp: 220,
    attack: 32,
    defense: 16,
    xpReward: 320,
    goldReward: 160,
    lootTable: [
      { itemId: "dragonbone-blade",       chance: 0.20 },
      { itemId: "dragonscale-armor",      chance: 0.22 },
      { itemId: "amulet-of-the-champion", chance: 0.15 },
      { itemId: "staff-of-ages",          chance: 0.12 },
      { itemId: "godslayer",              chance: 0.05 },
      { itemId: "celestial-aegis",        chance: 0.05 },
      { itemId: "heart-of-the-cosmos",    chance: 0.04 },
      { itemId: "elixir-of-life",         chance: 0.08 },
    ],
    description: "The ultimate challenge. Few have survived.",
  },
];
