import type { MonsterDef } from '@/types';

export const MONSTER_CATALOG: MonsterDef[] = [
  {
    id: 'goblin-scout',
    name: 'Goblin Scout',
    level: 1,
    hp: 30,
    attack: 8,
    defense: 2,
    xpReward: 20,
    goldReward: 10,
    lootTable: [
      { itemId: 'worn-sword', chance: 0.18 },
      { itemId: 'leather-vest', chance: 0.12 },
      { itemId: 'health-charm', chance: 0.1 },
      { itemId: 'minor-health-potion', chance: 0.15 },
    ],
    description: 'A small, quick goblin — your first real test.',
    flee: { chance: 0.3, thresholdPct: 0.25 },
    passive: { id: 'thorns', label: 'Spiked Hide', value: 10 },
  },
  {
    id: 'giant-rat',
    name: 'Giant Rat',
    level: 1,
    hp: 22,
    attack: 9,
    defense: 1,
    xpReward: 18,
    goldReward: 8,
    lootTable: [
      { itemId: 'stamina-band', chance: 0.18 },
      { itemId: 'health-charm', chance: 0.14 },
      { itemId: 'minor-health-potion', chance: 0.15 },
    ],
    description: 'Fast and feral. Low defense but bites hard.',
    flee: { chance: 0.35, thresholdPct: 0.25 },
    passive: { id: 'thorns', label: 'Jagged Claws', value: 12 },
  },
  {
    id: 'forest-goblin',
    name: 'Forest Goblin',
    level: 2,
    hp: 45,
    attack: 10,
    defense: 3,
    xpReward: 32,
    goldReward: 16,
    lootTable: [
      { itemId: 'worn-sword', chance: 0.2 },
      { itemId: 'hunters-bow', chance: 0.15 },
      { itemId: 'leather-vest', chance: 0.14 },
      { itemId: 'minor-health-potion', chance: 0.18 },
      { itemId: 'health-potion', chance: 0.08 },
    ],
    description: 'Armed with a crude axe and a chip on its shoulder.',
    flee: { chance: 0.3, thresholdPct: 0.25 },
    passive: { id: 'regen', label: 'Hardy', value: 2 },
  },
  {
    id: 'orc-grunt',
    name: 'Orc Grunt',
    level: 3,
    hp: 60,
    attack: 13,
    defense: 5,
    xpReward: 50,
    goldReward: 25,
    lootTable: [
      { itemId: 'hunters-bow', chance: 0.2 },
      { itemId: 'padded-robe', chance: 0.18 },
      { itemId: 'iron-sword', chance: 0.1 },
      { itemId: 'health-potion', chance: 0.12 },
    ],
    description: 'Thick-skinned and relentless. Respect the club.',
    active: { id: 'enrage', triggerPct: 0.5, label: 'Enrage', value: 4 },
  },
  {
    id: 'cave-spider',
    name: 'Cave Spider',
    level: 4,
    hp: 50,
    attack: 15,
    defense: 3,
    xpReward: 65,
    goldReward: 33,
    lootTable: [
      { itemId: 'stamina-band', chance: 0.22 },
      { itemId: 'twin-daggers', chance: 0.12 },
      { itemId: 'chain-shirt', chance: 0.1 },
      { itemId: 'health-potion', chance: 0.1 },
    ],
    description: 'Venomous and fast. It will overwhelm the unprepared.',
    flee: { chance: 0.25, thresholdPct: 0.2 },
    passive: { id: 'thorns', label: 'Venomous Spines', value: 18 },
  },
  {
    id: 'skeleton-warrior',
    name: 'Skeleton Warrior',
    level: 5,
    hp: 80,
    attack: 15,
    defense: 7,
    xpReward: 85,
    goldReward: 43,
    lootTable: [
      { itemId: 'chain-shirt', chance: 0.2 },
      { itemId: 'iron-sword', chance: 0.18 },
      { itemId: 'warriors-pendant', chance: 0.12 },
      { itemId: 'health-potion', chance: 0.12 },
    ],
    description: 'Animated by dark magic. High defense — chip it down.',
    passive: { id: 'regen', label: 'Undying', value: 4 },
    specialMoves: [
      {
        id: 'bone-crusher',
        name: 'Bone Crusher',
        emoji: '🦴',
        chance: 0.12,
        effect: { kind: 'heavy', multiplier: 1.5 },
      },
    ],
  },
  {
    id: 'dark-wolf',
    name: 'Dark Wolf',
    level: 6,
    hp: 90,
    attack: 18,
    defense: 5,
    xpReward: 105,
    goldReward: 53,
    lootTable: [
      { itemId: 'twin-daggers', chance: 0.22 },
      { itemId: 'stamina-band', chance: 0.2 },
      { itemId: 'shadowweave-cloak', chance: 0.08 },
      { itemId: 'phantom-blades', chance: 0.05 },
      { itemId: 'greater-health-potion', chance: 0.08 },
    ],
    description: 'Hunts in shadows. Ferocious and hungry.',
    flee: { chance: 0.25, thresholdPct: 0.2 },
    active: { id: 'enrage', triggerPct: 0.4, label: 'Blood Frenzy', value: 5 },
    specialMoves: [
      {
        id: 'rending-bite',
        name: 'Rending Bite',
        emoji: '🐺',
        chance: 0.15,
        effect: { kind: 'pierce' },
      },
    ],
  },
  {
    id: 'stone-troll',
    name: 'Stone Troll',
    level: 7,
    hp: 120,
    attack: 20,
    defense: 9,
    xpReward: 135,
    goldReward: 68,
    lootTable: [
      { itemId: 'battle-plate', chance: 0.22 },
      { itemId: 'warriors-pendant', chance: 0.2 },
      { itemId: 'iron-sword', chance: 0.18 },
      { itemId: 'titan-plate', chance: 0.06 },
      { itemId: 'greater-health-potion', chance: 0.1 },
    ],
    description: 'Nearly indestructible. Bring your best stats.',
    passive: { id: 'regen', label: 'Trollish Resilience', value: 6 },
    specialMoves: [
      {
        id: 'boulder-smash',
        name: 'Boulder Smash',
        emoji: '🪨',
        chance: 0.18,
        effect: { kind: 'heavy', multiplier: 1.7 },
      },
    ],
  },
  {
    id: 'dark-mage',
    name: 'Dark Mage',
    level: 8,
    hp: 95,
    // ATK 25 → 20, vampiric 30 → 20: magic + vampiric combo was flatly fatal for
    // Warriors at L8 before meaningful gear; reduced to survivable-but-threatening.
    attack: 20,
    defense: 4,
    attackType: 'magic',
    xpReward: 160,
    goldReward: 80,
    lootTable: [
      { itemId: 'arcane-tome', chance: 0.22 },
      { itemId: 'ring-of-wisdom', chance: 0.2 },
      { itemId: 'staff-of-ages', chance: 0.1 },
      { itemId: 'void-tome', chance: 0.07 },
      { itemId: 'greater-health-potion', chance: 0.1 },
    ],
    description: 'Glass cannon. Kill it fast or get obliterated.',
    passive: { id: 'vampiric', label: 'Life Tap', value: 20 },
    specialMoves: [
      {
        id: 'dark-nova',
        name: 'Dark Nova',
        emoji: '🌑',
        chance: 0.15,
        effect: { kind: 'heavy', multiplier: 1.5 },
      },
    ],
  },
  {
    id: 'lich-king',
    name: 'Lich King',
    level: 9,
    hp: 150,
    // ATK 28 → 24: magic + drain was fatal for Warriors pre-gear; still the hardest
    // pre-gateway monster but no longer a guaranteed wipe without consumables.
    attack: 24,
    defense: 9,
    attackType: 'magic',
    xpReward: 220,
    goldReward: 110,
    lootTable: [
      { itemId: 'staff-of-ages', chance: 0.18 },
      { itemId: 'void-tome', chance: 0.16 },
      { itemId: 'necrotic-staff', chance: 0.14 },
      { itemId: 'specter-shroud', chance: 0.1 },
      { itemId: 'ring-of-wisdom', chance: 0.18 },
      { itemId: 'greater-magic-potion', chance: 0.1 },
    ],
    description: 'A necromancer-king risen from death. Bring magic resistance or kneel.',
    active: { id: 'harden', triggerPct: 0.5, label: 'Bone Shield', value: 6 },
    specialMoves: [
      {
        id: 'soul-harvest',
        name: 'Soul Harvest',
        emoji: '👻',
        chance: 0.15,
        effect: { kind: 'drain', pct: 35 },
      },
    ],
  },
  {
    id: 'ancient-dragon',
    name: 'Ancient Dragon',
    level: 10,
    // HP 240 → 205 / ATK 32 → 30: the 1-round ability cooldown lengthens fights
    // (less DPS), which tipped the off-affinity Wizard + the slow-killing Rogue
    // past 100% HP-loss at this gateway boss. Trimmed to stay winnable.
    hp: 205,
    attack: 30,
    defense: 16,
    xpReward: 320,
    goldReward: 160,
    lootTable: [
      { itemId: 'dragonbone-blade', chance: 0.2 },
      { itemId: 'dragonscale-armor', chance: 0.22 },
      { itemId: 'amulet-of-the-champion', chance: 0.15 },
      { itemId: 'staff-of-ages', chance: 0.12 },
      { itemId: 'godslayer', chance: 0.05 },
      { itemId: 'celestial-aegis', chance: 0.05 },
      { itemId: 'heart-of-the-cosmos', chance: 0.04 },
      { itemId: 'elixir-of-life', chance: 0.08 },
    ],
    description: 'The ultimate challenge. Few have survived.',
    passive: { id: 'thorns', label: 'Dragon Scales', value: 25 },
    specialMoves: [
      {
        id: 'dragonfire',
        name: 'Dragonfire',
        emoji: '🔥',
        chance: 0.15,
        effect: { kind: 'burst' },
      },
    ],
  },

  // ── Content-scaling PR2: new monsters ────────────────────────────────────────
  // Filling out levels 1–10 variety and the level 11–14 progression gap between
  // Ancient Dragon (10) and Dragon King boss (15). New mechanics: `siphon`
  // (stamina drain on hit), `armor-pierce` (flat DEF reduction), `summon-add`
  // (one-time HP boost on threshold). Drop tables reference existing items
  // until PR3 lands the L11–14 gear — missing item IDs are gracefully skipped
  // by rollLoot.
  {
    id: 'mud-imp',
    name: 'Mud Imp',
    level: 1,
    hp: 25,
    attack: 9,
    defense: 1,
    xpReward: 19,
    goldReward: 9,
    lootTable: [
      { itemId: 'leather-vest', chance: 0.16 },
      { itemId: 'stamina-band', chance: 0.14 },
      { itemId: 'minor-stamina-potion', chance: 0.18 },
    ],
    description: 'Sticky little brawler. Its grip saps your strength.',
    flee: { chance: 0.35, thresholdPct: 0.25 },
    passive: { id: 'siphon', label: 'Sticky Grip', value: 1 },
  },
  {
    id: 'boar-runt',
    name: 'Boar Runt',
    level: 2,
    hp: 50,
    attack: 11,
    defense: 3,
    xpReward: 36,
    goldReward: 18,
    lootTable: [
      { itemId: 'hunters-bow', chance: 0.18 },
      { itemId: 'leather-vest', chance: 0.16 },
      { itemId: 'minor-health-potion', chance: 0.2 },
    ],
    description: 'Charges first, regrets later — until it sees red.',
    flee: { chance: 0.25, thresholdPct: 0.2 },
    active: { id: 'enrage', triggerPct: 0.5, label: 'Tusk Charge', value: 3 },
  },
  {
    id: 'bog-lurker',
    name: 'Bog Lurker',
    level: 4,
    hp: 70,
    attack: 14,
    defense: 4,
    xpReward: 70,
    goldReward: 35,
    lootTable: [
      { itemId: 'twin-daggers', chance: 0.14 },
      { itemId: 'chain-shirt', chance: 0.12 },
      { itemId: 'minor-stamina-potion', chance: 0.2 },
      { itemId: 'health-potion', chance: 0.12 },
    ],
    description: 'Drags you into the muck. Each grasp pulls the stamina from your arms.',
    passive: { id: 'siphon', label: 'Mire Grasp', value: 2 },
  },
  {
    id: 'iron-husk',
    name: 'Iron Husk',
    level: 5,
    hp: 95,
    attack: 14,
    defense: 9,
    xpReward: 90,
    goldReward: 45,
    lootTable: [
      { itemId: 'chain-shirt', chance: 0.22 },
      { itemId: 'iron-sword', chance: 0.16 },
      { itemId: 'warriors-pendant', chance: 0.1 },
      { itemId: 'health-potion', chance: 0.12 },
    ],
    description: 'A walking suit of cursed plate. Punches through whatever you wear.',
    passive: { id: 'armor-pierce', label: 'Sundering Strike', value: 2 },
    active: { id: 'heal', triggerPct: 0.4, label: 'Self-Repair', value: 28 },
    specialMoves: [
      {
        id: 'iron-haymaker',
        name: 'Iron Haymaker',
        emoji: '🤜',
        chance: 0.15,
        effect: { kind: 'heavy', multiplier: 1.6 },
      },
    ],
  },
  {
    id: 'frost-wraith',
    name: 'Frost Wraith',
    level: 6,
    hp: 80,
    attack: 19,
    defense: 4,
    attackType: 'magic',
    xpReward: 110,
    goldReward: 56,
    lootTable: [
      { itemId: 'arcane-tome', chance: 0.18 },
      { itemId: 'ring-of-wisdom', chance: 0.16 },
      { itemId: 'shadowweave-cloak', chance: 0.09 },
      { itemId: 'magic-potion', chance: 0.15 },
    ],
    description: 'Cold ghost. Your arms go numb where it touches you.',
    passive: { id: 'siphon', label: 'Numbing Chill', value: 3 },
    specialMoves: [
      {
        id: 'soul-frost',
        name: 'Soul Frost',
        emoji: '❄️',
        chance: 0.15,
        effect: { kind: 'drain', pct: 30 },
      },
    ],
  },
  {
    id: 'gloom-knight',
    name: 'Gloom Knight',
    level: 8,
    hp: 130,
    attack: 24,
    defense: 8,
    xpReward: 165,
    goldReward: 84,
    lootTable: [
      { itemId: 'battle-plate', chance: 0.2 },
      { itemId: 'iron-sword', chance: 0.18 },
      { itemId: 'specter-shroud', chance: 0.08 },
      { itemId: 'phantom-blades', chance: 0.05 },
      { itemId: 'greater-health-potion', chance: 0.1 },
    ],
    description: 'A fallen paladin. The oath broke; the steel did not.',
    active: { id: 'harden', triggerPct: 0.4, label: 'Oathbreaker Bulwark', value: 5 },
    specialMoves: [
      {
        id: 'oathbreaker-cleave',
        name: 'Oathbreaker Cleave',
        emoji: '🗡️',
        chance: 0.15,
        effect: { kind: 'pierce' },
      },
    ],
  },
  {
    id: 'obsidian-golem',
    name: 'Obsidian Golem',
    level: 11,
    hp: 255,
    attack: 28,
    defense: 16,
    xpReward: 260,
    goldReward: 130,
    lootTable: [
      { itemId: 'dragonbone-blade', chance: 0.12 },
      { itemId: 'titan-plate', chance: 0.1 },
      { itemId: 'amulet-of-the-champion', chance: 0.08 },
      { itemId: 'greater-stamina-potion', chance: 0.12 },
      { itemId: 'guardian-bulwark', chance: 0.03 },
      { itemId: 'titan-elixir', chance: 0.08 },
    ],
    description: 'A living statue from the Keep depths. Volcanic glass cleaves through plate.',
    passive: { id: 'armor-pierce', label: 'Volcanic Edge', value: 4 },
    specialMoves: [
      {
        id: 'magma-crush',
        name: 'Magma Crush',
        emoji: '🌋',
        chance: 0.18,
        effect: { kind: 'heavy', multiplier: 1.7 },
      },
    ],
  },
  {
    id: 'ashwyrm',
    name: 'Ashwyrm',
    level: 12,
    hp: 290,
    // ATK 32 → 27: magic attacker + thorns combo was fatal for Warriors at L12;
    // reduced to ~85% HP loss so it remains the scariest endgame approach monster.
    attack: 27,
    defense: 14,
    attackType: 'magic',
    xpReward: 300,
    goldReward: 150,
    lootTable: [
      { itemId: 'dragonscale-armor', chance: 0.14 },
      { itemId: 'stormcleaver', chance: 0.08 },
      { itemId: 'void-tome', chance: 0.08 },
      { itemId: 'amulet-of-the-champion', chance: 0.1 },
      { itemId: 'elixir-of-life', chance: 0.06 },
      { itemId: 'world-ender', chance: 0.03 },
      { itemId: 'phoenix-feather', chance: 0.06 },
      { itemId: 'spell-stellar-collapse', chance: 0.03 },
    ],
    description: 'Lesser dragon, smouldering breath. Its hide burns to the touch.',
    passive: { id: 'thorns', label: 'Cinder Hide', value: 22 },
    specialMoves: [
      {
        id: 'ember-cyclone',
        name: 'Ember Cyclone',
        emoji: '🔥',
        chance: 0.15,
        effect: { kind: 'heavy', multiplier: 1.6 },
      },
    ],
  },
  {
    id: 'void-revenant',
    name: 'Void Revenant',
    level: 13,
    // HP 285 → 205 / ATK 34 → 27: armor-ignoring magic + summon-add + drain stack
    // a long grind of unmitigated damage that, with the ability-cooldown DPS hit,
    // tipped the magic-fearing Warrior and the slow-killing Rogue past 100%
    // HP-loss. Trimmed across two passes; still threatening via its mechanics.
    hp: 205,
    attack: 27,
    defense: 12,
    attackType: 'magic',
    xpReward: 340,
    goldReward: 170,
    lootTable: [
      { itemId: 'void-tome', chance: 0.12 },
      { itemId: 'specter-shroud', chance: 0.1 },
      { itemId: 'heart-of-the-cosmos', chance: 0.05 },
      { itemId: 'greater-magic-potion', chance: 0.15 },
      { itemId: 'cosmic-codex', chance: 0.03 },
      { itemId: 'eye-of-eternity', chance: 0.04 },
      { itemId: 'arcane-elixir', chance: 0.08 },
      { itemId: 'spell-thousand-cuts', chance: 0.03 },
    ],
    description: 'Echo of a fallen hero. Reinforcements emerge from the void mid-fight.',
    active: { id: 'summon-add', triggerPct: 0.5, label: 'Echo Reinforcements', value: 40 },
    specialMoves: [
      {
        id: 'void-siphon',
        name: 'Void Siphon',
        emoji: '🕳️',
        chance: 0.18,
        effect: { kind: 'drain', pct: 40 },
      },
    ],
  },
  {
    id: 'storm-djinn',
    name: 'Storm Djinn',
    level: 14,
    hp: 335,
    // ATK 40 → 34 (#173, magic typing) → 32 → 26: model treats Djinn as the L20
    // capstone but it appears in arena for L13–15 players — 6-level mismatch means
    // Warriors were dying in 2.6 rounds. Vampiric 25 → 15 cuts effective HP padding.
    attack: 26,
    defense: 14,
    attackType: 'magic',
    xpReward: 400,
    goldReward: 200,
    lootTable: [
      { itemId: 'stormcleaver', chance: 0.15 },
      { itemId: 'celestial-aegis', chance: 0.06 },
      { itemId: 'heart-of-the-cosmos', chance: 0.05 },
      { itemId: 'godslayer', chance: 0.04 },
      { itemId: 'elixir-of-life', chance: 0.08 },
      { itemId: 'shadowblade-zenith', chance: 0.03 },
      { itemId: 'twin-suns-pendant', chance: 0.04 },
      { itemId: 'storm-stride', chance: 0.06 },
      { itemId: 'phoenix-draught', chance: 0.02 },
      { itemId: 'spell-worldbreaker', chance: 0.03 },
    ],
    description: 'Air elemental, lightning lash. Drinks your blood like rain.',
    passive: { id: 'vampiric', label: 'Skyfeast', value: 15 },
    active: { id: 'enrage', triggerPct: 0.3, label: 'Tempest Wrath', value: 6 },
    specialMoves: [
      {
        id: 'thunderlance',
        name: 'Thunderlance',
        emoji: '⚡',
        chance: 0.15,
        effect: { kind: 'pierce' },
      },
      {
        id: 'tempest-crash',
        name: 'Tempest Crash',
        emoji: '🌪️',
        chance: 0.12,
        effect: { kind: 'heavy', multiplier: 1.7 },
      },
      {
        id: 'thunderclap',
        name: 'Thunderclap',
        emoji: '💫',
        chance: 0.1,
        effect: { kind: 'stun' },
      },
    ],
  },
];

const MONSTER_BY_ID = new Map(MONSTER_CATALOG.map((m) => [m.id, m]));

/** Map-backed catalog lookup by monster id. */
export function getMonsterById(id: string): MonsterDef | undefined {
  return MONSTER_BY_ID.get(id);
}
